name: CD - Deploy on Merge to Develop

on:
  pull_request:
    types: [closed]
    branches:
      - develop 

env:
  AZURE_FUNCTIONAPP_NAME: 'oktatest-func'
  PYTHON_VERSION: '3.10'
  PACKAGE_NAME: '.'


jobs:
  deploy:
    if: github.event.pull_request.merged == true   # chỉ chạy khi merge, không chạy khi chỉ closed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true
          func --version

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.PACKAGE_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          sku: flexconsumption
          remote-build: false
          scm-do-build-during-deployment: false
          enable-oryx-build: false